### ISSUE TITLE
Syntax error on lib import

### ISSUE THREAD

**Issue by mohamedhayibor** [circle-free/merkle-trees#22]
Tried quickly playing with it but on the repl, it spits out errors:

```js
> const { MerkleTree } = require('merkle-trees/js');
/Users/mo/Desktop/my-forks/npm-package-test/node_modules/merkle-trees/js/src/merkle-trees.js:128
      return { root: merkleTree.root, elementCount: appendElements?.length ?? 1 };
                                                                   ^

SyntaxError: Unexpected token .
```

$ node -v
v10.15.0

$ npm -v
6.14.5

**Comment by deluca-mike** [comment]
Hey @mohamedhayibor, this library works with node v14+, which introduced [Optional Chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).

I would recommend upgrading your node engine, if your project allows.

**Comment by mohamedhayibor** [comment]
Ah, I see. Very interesting 🚀  I'll hop into node v14+ soon. 😅
